[package]
name = "slime"
version = "0.1.0"
authors = ["Zelda Hessler <zelda.hessler@tempus.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = []
midi = ["midir", "midly"]

[dependencies]
circular-queue = "0.2.6"
colorgrad = "0.4.0"
config = "0.11.0"
dotenv = "0.15.0"
env_logger = "0.8.3"
grid = "0.2.3"
image = "0.23.14"
imageproc = "0.22.0"
log = "0.4.14"
midir = { version = "0.7.0", optional = true }
midly = { version = "0.5.1", optional = true }
notify = "5.0.0-pre.7"
num = "0.4.0"
pixels = "0.3.0"
rand = { version = "0.8.3", features = ["small_rng"] }
rayon = "1.5.0"
serde = { version = "1.0.125", features = ["derive"] }
thiserror = "1.0.24"
typed-builder = "0.9.0"
winit = "0.24.0"
winit_input_helper = "0.9.0"
