[package]
name = "slime"
version = "0.1.0"
authors = ["Zelda Hessler <zelda.hessler@tempus.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.8.3"
grid = "0.2.3"
log = "0.4.14"
num = "0.4.0"
pixels = "0.2.0"
rand = { version = "0.8.3", features = ["small_rng"] }
typed-builder = "0.9.0"
winit = "0.24.0"
winit_input_helper = "0.9.0"
