# This is TOML
# Copy this and start editing it to save your own personal settings

# General settings
# I'm not yet sure how I want to handle resizes
windowWidth = 1920
windowHeight = 1080
windowFullscreen = false

# Agent settings
agentCount = 500000
agentJitter = 0.0
# Min must always be < Max
agentSpeedMin = 10.0
agentSpeedMax = 1000.0
agentTurnSpeed = 2.0
agentSensorAngle = 0.3
agentSensorDistance = 30.0

# Pheromone settings
pheromoneDepositionAmount = 1.0
pheromoneDecayFactor = 10.0
pheromoneDiffusionRate = 1.0

[agentPossibleStartingHeadings]
start = 0.0
end = 360.0
