# This is TOML
# Copy this and start editing it to save your own personal settings

# General settings
# I'm not yet sure how I want to handle resizes
windowWidth = 1600
windowHeight = 900
windowFullscreen = false

# Agent settings
agentCount = 10_000_000
agentJitter = 0.0
# Min must always be < Max
agentSpeedMin = 70.0
agentSpeedMax = 80.0
agentTurnSpeed = 1.0
agentSensorAngle = 0.3
agentSensorDistance = 20.0

# Pheromone settings
pheromoneDepositionAmount = 0.001
pheromoneDecayFactor = 1.0
pheromoneDiffusionRate = 0.001

[agentPossibleStartingHeadings]
start = 0.0
end = 360.0
